blueprint:
  name: 💡 Standby-Killer für Steckdosen (funktionierend)
  description: >
    Schaltet eine Steckdose automatisch aus, wenn der Verbrauch für eine bestimmte Zeit
    unter einen definierten Watt-Wert fällt. Optional kann ein Helfer die Funktion deaktivieren.

    ✅ Trigger basiert auf numeric_state
    ✅ Optionaler "Standby-Killer AUS"-Helfer korrekt eingebunden
    ✅ Funktioniert mit allen Leistungssensoren (Watt)
    ✅ Inklusive Logbuchmeldung zur Rückmeldung

  domain: automation
  input:
    power_sensor:
      name: Verbrauchssensor (Watt)
      selector:
        entity:
          domain: sensor

    plug_switch:
      name: Steckdose
      selector:
        entity:
          domain: switch

    watt_threshold:
      name: Verbrauchsschwelle (Watt)
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: W

    wait_time:
      name: Wartezeit unterhalb der Schwelle
      default: "00:00:20"
      selector:
        duration:

    abschalt_sperre:
      name: Standby-Killer AUS (optional)
      description: Wenn dieser Schalter auf AN steht, wird nicht abgeschaltet.
      default: ""
      selector:
        entity:
          domain: input_boolean
          multiple: false

trigger:
  - platform: numeric_state
    entity_id: !input power_sensor
    below: !input watt_threshold
    for: !input wait_time

condition:
  - condition: state
    entity_id: !input plug_switch
    state: "on"

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: template
                value_template: >
                  {{ not inputs.get('abschalt_sperre') }}
              - condition: template
                value_template: >
                  {{ is_state(inputs.get('abschalt_sperre'), 'off') }}
        sequence:
          - service: logbook.log
            data:
              name: "Standby-Killer"
              message: >
                Verbrauch unter {{ inputs['watt_threshold'] }} W –
                Steckdose {{ states[inputs['plug_switch']].name }} wird ausgeschaltet.
          - service: switch.turn_off
            target:
              entity_id: !input plug_switch

mode: single
