blueprint:
  name: ⚡ Einfacher Standby-Killer
  description: >
    🧠 Version: 1.0  
    📅 Erstellt: Mai 2025  
    ✍️ Autor: Martin

    💡 Beschreibung:
    Diese Automation schaltet eine Steckdose automatisch aus,
    wenn der zugehörige Verbrauchssensor über eine bestimmte Dauer
    unterhalb einer definierten Watt-Schwelle liegt.

    ✅ Ideal für Fernseher, Drucker, Soundsysteme u. ä.  
    ✅ Einfach zu konfigurieren  
    ✅ Funktioniert ohne zusätzliche Helfer oder Bedingungstricks  
    ✅ Übersichtliche Logmeldung im Logbuch bei Auslösung

    Eingabefelder:
    - Verbrauchssensor: Sensor, der Leistung in Watt liefert (z. B. Shelly, Gosund, Homematic)
    - Steckdose: Die zu schaltende Steckdose
    - Verbrauchsschwelle: Grenzwert in Watt (Standard: 10 W)
    - Wartezeit: Wie lange der Wert unterhalb der Schwelle bleiben muss

  domain: automation

  input:
    power_sensor:
      name: Verbrauchssensor (Watt)
      selector:
        entity:
          domain: sensor
    plug_switch:
      name: Steckdose
      selector:
        entity:
          domain: switch
    watt_threshold:
      name: Verbrauchsschwelle
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: W
          step: 1
    wait_time:
      name: Wartezeit unterhalb der Schwelle
      default: "00:00:20"
      selector:
        duration:

trigger:
  - platform: numeric_state
    entity_id: !input power_sensor
    below: !input watt_threshold
    for: !input wait_time

condition:
  - condition: state
    entity_id: !input plug_switch
    state: "on"

action:
  - service: logbook.log
    data:
      name: "Standby-Killer"
      message: "Verbrauch unter Schwelle – Steckdose wird ausgeschaltet."
  - service: switch.turn_off
    target:
      entity_id: !input plug_switch

mode: single
