blueprint:
  name: 💡 Standby-Killer für Steckdosen (optional abschaltbar)
  description: >
    Version: 1.2.0  
    Erstellt: Mai 2025  
    Autor: Martin  

    💡 Automatisches Abschalten einer Steckdose bei dauerhaft niedrigem Stromverbrauch.

    ✅ Ideal für TV, Hi-Fi, Drucker  
    ✅ Schwellwert in ganzen Watt (max. 100 W)  
    ✅ Einstellbare Wartezeit (1 Min. – 24 Std.)  
    ✅ Optional deaktivierbar (Standby-Killer AUS)  

    Änderungen:
    - v1.2.0: Fehlerfreie YAML- & Jinja-Logik implementiert

  domain: automation
  input:
    power_sensor:
      name: 🔌 Verbrauchssensor
      selector:
        entity:
          domain: sensor

    plug_switch:
      name: 🧠 Steckdose
      selector:
        entity:
          domain: switch

    watt_threshold:
      name: ⚡ Verbrauchsschwelle (Watt)
      default: 5
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: W
          mode: slider

    wait_time:
      name: ⏳ Wartezeit
      default: "02:00:00"
      selector:
        duration:

    abschalt_sperre:
      name: 🚫 Standby-Killer AUS (optional)
      description: >
        Optionaler Schalter: Wenn auf AN, keine automatische Abschaltung.
      default: ""
      selector:
        entity:
          domain: input_boolean
          multiple: false

trigger:
  - platform: numeric_state
    entity_id: !input power_sensor
    below: !input watt_threshold
    for: !input wait_time

condition:
  - condition: state
    entity_id: !input plug_switch
    state: "on"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ inputs.get('abschalt_sperre') in [none, ''] or is_state(inputs.get('abschalt_sperre'), 'off') }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input plug_switch
mode: single
