blueprint:
  name: ⚡ Einfacher Standby-Killer
  description: >
    Schaltet eine Steckdose aus, wenn ein Leistungssensor
    für eine definierte Zeit unter einem Schwellwert liegt.
  domain: automation
  input:
    power_sensor:
      name: Verbrauchssensor (Watt)
      selector:
        entity:
          domain: sensor
    plug_switch:
      name: Steckdose
      selector:
        entity:
          domain: switch
    watt_threshold:
      name: Verbrauchsschwelle
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: W
          step: 1
    wait_time:
      name: Wartezeit unterhalb der Schwelle
      default: "00:00:20"
      selector:
        duration:

trigger:
  - platform: numeric_state
    entity_id: !input power_sensor
    below: !input watt_threshold
    for: !input wait_time

condition:
  - condition: state
    entity_id: !input plug_switch
    state: "on"

action:
  - service: logbook.log
    data:
      name: "Standby-Killer"
      message: >
        Verbrauch unter {{ states(!input power_sensor) }} W –
        schalte {{ states(!input plug_switch).name }} aus
  - service: switch.turn_off
    target:
      entity_id: !input plug_switch

mode: single
