blueprint:
  name: 💡 Standby-Killer für Steckdosen (mit optionalem AUS-Schalter)
  description: >
    Version: 1.3.0  
    Autor: Martin  
    Dieser Blueprint schaltet eine Steckdose automatisch ab, wenn der Stromverbrauch unter einen definierten Schwellenwert fällt – optional deaktivierbar über einen Umschalter.
  domain: automation

  input:
    power_sensor:
      name: 🔌 Verbrauchssensor
      selector:
        entity:
          domain: sensor
    plug_switch:
      name: 🧠 Steckdose
      selector:
        entity:
          domain: switch
    watt_threshold:
      name: ⚡ Verbrauchsschwelle (Watt)
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: W
    wait_time:
      name: ⏳ Wartezeit
      default: "02:00:00"
      selector:
        duration:
    abschalt_sperre:
      name: 🚫 Standby-Killer AUS (optional)
      description: Wenn dieser Schalter auf AN steht, wird die Automation unterdrückt.
      default: ""
      selector:
        entity:
          domain: input_boolean
          multiple: false

trigger:
  - platform: numeric_state
    entity_id: !input power_sensor
    below: !input watt_threshold
    for: !input wait_time

condition:
  - condition: state
    entity_id: !input plug_switch
    state: "on"

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: template
                value_template: >
                  {{ not (inputs.get('abschalt_sperre')) }}
              - condition: template
                value_template: >
                  {{ is_state(inputs.get('abschalt_sperre'), 'off') }}
        sequence:
          - service: logbook.log
            data:
              name: "Standby-Killer"
              message: "Verbrauch unter Schwelle – Steckdose wird ausgeschaltet"
          - service: switch.turn_off
            target:
              entity_id: !input plug_switch
mode: single
